# Generated by Django 4.1.7 on 2023-03-24 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='За минуту даже на индукции не готовится.'), django.core.validators.MaxValueValidator(limit_value=300, message='Все сгорит.')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Количество должно быть больше нуля'), django.core.validators.MaxValueValidator(limit_value=30, message='Количество не может быть больше 30.')], verbose_name='Количество'),
        ),
    ]
